### PR TITLE
Setup initial repo with composer - resolves #7

### LINKED ISSUE #7: Set-up basic repo with composer, phpunit, etc.

### PR DESCRIPTION
**Pull request by garethellis36**

### CODE REVIEW

**Comment by garethellis36** [comment]
Would it be better to ignore this PR and re-start using @martindilling 's composer plugin?

**Comment by liquorvicar** [comment]
+1 to this PR. @martindilling 's repo is just a skel right? Not sure if we can automatically grab all the skel files into an existing repo or whether we need to start a new repo.

**Comment by garethellis36** [comment]
I think if we were to wipe this PR one could do composer create-project using @martindilling 's plugin and it would create the skeleton. I could then just edit the various settings files as necessary. Would address several of the setup tickets at once.

**Comment by liquorvicar** [comment]
If we can use the same repo, we can do that and then just rebase this PR on the latest version surely?

**Comment by garethellis36** [comment]
I think this PR would be redundant if we did that.

**Comment by ascii-soup** [comment]
I think this PR is redundant.
Let's just use Martin's skeleton.
1. Create a new project on your hard drive using his skeleton.
2. git init
3. git remote add origin git@github.com:phpoxford/spires.git
4. git add [files]
5. git commit
6. git push -uf origin master

Should work, no?

**Comment by liquorvicar** [comment]
That should work. We could probably still salvage this PR if we needed to but we can just manually copy across anything we need I guess anyway.

**Comment by garethellis36** [comment]
OK, I'll get on that now.

**Pull request closed without merging**
